# Generated by Django 3.2.3 on 2021-06-20 16:05

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=254)),
                ('club_badge_url', models.URLField(max_length=1024)),
                ('club_badge', models.ImageField(blank=True, null=True, upload_to='')),
                ('website_url', models.URLField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('referee_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('asst_referee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('nonpayment_fine', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('milage_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
                ('short_name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=80)),
                ('town_or_city', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=60)),
                ('postcode', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('map', models.ImageField(blank=True, null=True, upload_to='')),
                ('map_url', models.URLField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('manager_coach', models.CharField(max_length=100)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.fee')),
                ('club_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.club')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('asst_referee1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asst1', to='matches.official')),
                ('asst_referee2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asst2', to='matches.official')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='matches.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='matches.team')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref', to='matches.official')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.venue')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
