# Generated by Django 3.2.3 on 2021-05-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ko_time',
        ),
    ]
