# Generated by Django 3.2.3 on 2021-06-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='age_group', to='matches.fee'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.fee'),
        ),
    ]
