# Generated by Django 3.2.3 on 2021-06-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20210528_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['date_time']},
        ),
        migrations.AlterField(
            model_name='fee',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.game'),
        ),
    ]
