# Generated by Django 3.2.3 on 2021-06-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20210622_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='nonpayment_fine',
        ),
    ]
