# Generated by Django 3.2.3 on 2021-06-10 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20210610_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.age_group'),
        ),
    ]
