# Generated by Django 3.2.3 on 2021-06-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_fee_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='age',
        ),
        migrations.AlterField(
            model_name='fee',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.fee'),
        ),
        migrations.DeleteModel(
            name='Age_Group',
        ),
    ]
