# Generated by Django 3.2.3 on 2021-06-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20210610_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='asst_referee1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='asst_referee2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='referee',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
