# Generated by Django 3.2.3 on 2021-06-16 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20210616_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='asst_referee1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asst1', to='matches.official'),
        ),
        migrations.AlterField(
            model_name='game',
            name='asst_referee2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asst2', to='matches.official'),
        ),
        migrations.AlterField(
            model_name='game',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref', to='matches.official'),
        ),
    ]
