# Generated by Django 3.2.3 on 2021-07-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_country',
            new_name='profile_country',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_county',
            new_name='profile_county',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_phone_number',
            new_name='profile_phone_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_postcode',
            new_name='profile_postcode',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_street_address1',
            new_name='profile_street_address1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_street_address2',
            new_name='profile_street_address2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_town_or_city',
            new_name='profile_town_or_city',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_role',
            new_name='role',
        ),
    ]
