# Generated by Django 3.2.3 on 2021-06-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='country_or_state',
            new_name='county_or_state',
        ),
    ]
