# Generated by Django 3.2.3 on 2021-06-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20210622_0928'),
        ('checkout', '0002_rename_country_or_state_order_county_or_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='match_fines',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.fee'),
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
