# Generated by Django 3.2.3 on 2021-06-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210624_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='match_fines',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
