# Generated by Django 3.2.3 on 2021-06-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_remove_fee_nonpayment_fine'),
        ('checkout', '0004_alter_order_match_fines'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLineItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.game')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
            ],
        ),
    ]
