# Generated by Django 3.2.3 on 2021-07-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210705_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='match_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
