# Generated by Django 3.2.3 on 2021-07-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='original_bag',
            field=models.CharField(default='', max_length=200),
        ),
    ]
